## The following code creates an special kind of matrix object
## that can hold a cached value of its inverse.
## The *makeCacheMatrix* creates this special matrix and *cacheSolve*
## returns its inverse (a cached value, or calculates it if necessary)

## Creates a special object that holds a matrix and
## its inverse.
##
## The functions sets the inverse value to NULL by default,
## the value of the inverse can added via setinverse() method
## to be cached
##
## @param x: input matrix or an empty matrix by default
##
## @returns a set of getters and setters to manipulate the 
## held matrix and its inverse
makeCacheMatrix <- function (x = matrix()) {
    inverse <- NULL
    set <- function (mat) {
        x <<- mat
        inverse <<- NULL
    }
    get <- function () x
    setinverse <- function( new_inverse ) inverse <<- new_inverse
    getinverse <- function() inverse
    list( set = set, get = get, setinverse = setinverse, getinverse = getinverse )
}


## Calculates the inverse of the matrix held by the x object
## if it has not already a cached value for its inverse.
##
## It checks if the object already have a cached value
## for the inverse, if it has, return it. Otherwise, 
## calculates the inverse of the matrix, sets as inverse
## in the object and returns it
##
## @param x: object generated by the *makeCacheMatrix* 
## function that holds a matrix via get() method
##
## @returns the inverse of the matrix held by x
cacheSolve <- function(x, ...) {
    inverse <- x$getinverse()
    if (!is.null(inverse)) {
        message("getting cached data")
        return(inverse)
    }
    data <- x$get()
    inverse <- solve(data)
    x$setinverse(inverse)
    inverse
}
